// Mapeamento dos 66 Livros: ID -> { Nome, Quantidade de Capítulos }
export const BIBLE_DATA: { [key: number]: { name: string, chapters: number } } = {
    1: { name: 'Gênesis', chapters: 50 },
    2: { name: 'Êxodo', chapters: 40 },
    3: { name: 'Levítico', chapters: 27 },
    4: { name: 'Números', chapters: 36 },
    5: { name: 'Deuteronômio', chapters: 34 },
    6: { name: 'Josué', chapters: 24 },
    7: { name: 'Juízes', chapters: 21 },
    8: { name: 'Rute', chapters: 4 },
    9: { name: '1 Samuel', chapters: 31 },
    10: { name: '2 Samuel', chapters: 24 },
    11: { name: '1 Reis', chapters: 22 },
    12: { name: '2 Reis', chapters: 25 },
    13: { name: '1 Crônicas', chapters: 29 },
    14: { name: '2 Crônicas', chapters: 36 },
    15: { name: 'Esdras', chapters: 10 },
    16: { name: 'Neemias', chapters: 13 },
    17: { name: 'Ester', chapters: 10 },
    18: { name: 'Jó', chapters: 42 },
    19: { name: 'Salmos', chapters: 150 },
    20: { name: 'Provérbios', chapters: 31 },
    21: { name: 'Eclesiastes', chapters: 12 },
    22: { name: 'Cânticos', chapters: 8 },
    23: { name: 'Isaías', chapters: 66 },
    24: { name: 'Jeremias', chapters: 52 },
    25: { name: 'Lamentações', chapters: 5 },
    26: { name: 'Ezequiel', chapters: 48 },
    27: { name: 'Daniel', chapters: 12 },
    28: { name: 'Oseias', chapters: 14 },
    29: { name: 'Joel', chapters: 3 },
    30: { name: 'Amós', chapters: 9 },
    31: { name: 'Obadias', chapters: 1 },
    32: { name: 'Jonas', chapters: 4 },
    33: { name: 'Miqueias', chapters: 7 },
    34: { name: 'Naum', chapters: 3 },
    35: { name: 'Habacuque', chapters: 3 },
    36: { name: 'Sofonias', chapters: 3 },
    37: { name: 'Ageu', chapters: 2 },
    38: { name: 'Zacarias', chapters: 14 },
    39: { name: 'Malaquias', chapters: 4 },
    40: { name: 'Mateus', chapters: 28 },
    41: { name: 'Marcos', chapters: 16 },
    42: { name: 'Lucas', chapters: 24 },
    43: { name: 'João', chapters: 21 },
    44: { name: 'Atos', chapters: 28 },
    45: { name: 'Romanos', chapters: 16 },
    46: { name: '1 Coríntios', chapters: 16 },
    47: { name: '2 Coríntios', chapters: 13 },
    48: { name: 'Gálatas', chapters: 6 },
    49: { name: 'Efésios', chapters: 6 },
    50: { name: 'Filipenses', chapters: 4 },
    51: { name: 'Colossenses', chapters: 4 },
    52: { name: '1 Tessalonicenses', chapters: 5 },
    53: { name: '2 Tessalonicenses', chapters: 3 },
    54: { name: '1 Timóteo', chapters: 6 },
    55: { name: '2 Timóteo', chapters: 4 },
    56: { name: 'Tito', chapters: 3 },
    57: { name: 'Filemom', chapters: 1 },
    58: { name: 'Hebreus', chapters: 13 },
    59: { name: 'Tiago', chapters: 5 },
    60: { name: '1 Pedro', chapters: 5 },
    61: { name: '2 Pedro', chapters: 3 },
    62: { name: '1 João', chapters: 5 },
    63: { name: '2 João', chapters: 1 },
    64: { name: '3 João', chapters: 1 },
    65: { name: 'Judas', chapters: 1 },
    66: { name: 'Apocalipse', chapters: 22 }
  };